build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
labels:
  org.opencontainers.image.title: "Hello World Add-on"
  org.opencontainers.image.description: "A simple Hello World add-on for Home Assistant"
  org.opencontainers.image.source: https://github.com/Ahmed9190/hello-world-addon
  org.opencontainers.image.licenses: Apache License 2.0
